let bookNameInput = prompt("Nhập tên sách:");
let authorInput = prompt("Nhập tên tác giả:");
let publishYear = Number(prompt("Nhập năm xuất bản:"));
let price = Number(prompt("Nhập giá tiền một cuốn:"));
let quantity = Number(prompt("Nhập số lượng nhập kho:"));
let cleanBookName = bookNameInput.trim().toUpperCase();
let cleanAuthor = authorInput.toUpperCase();
let authorPrefix = cleanAuthor.slice(0, 3);
let randomIdNum = Math.floor(Math.random() * 1000) + 1;
let bookId = `${authorPrefix}${publishYear}-${randomIdNum}`;
const CURRENT_YEAR = 2026;
let bookAge = CURRENT_YEAR - publishYear;
let totalValue = price * quantity;
let shelfNumber = Math.floor(Math.random() * 10) + 1;
console.log(`--- PHIẾU NHẬP KHO ---`);
console.log(`Mã sách: ${bookId}`);
console.log(`Tên sách: ${cleanBookName}`);
console.log(`Tác giả: ${cleanAuthor}`);
console.log(`Năm xuất bản: ${publishYear}`);
console.log(`Tuổi sách: ${bookAge} năm`);
console.log(`Tổng giá trị: ${totalValue} VNĐ`);
console.log(`Ngăn kệ gợi ý: Kệ số ${shelfNumber}`);